/* GENERATED by scripts/check_tokens.ts — do not edit.
 * Source of truth: src/lib/tokens.ts. Run `npm run check:tokens -- --write`.
 */
module.exports = {
  "colors": {
    "ink": "#0f0d0a",
    "surface": "#181510",
    "raised": "#211d15",
    "line": "rgba(236, 231, 220, 0.08)",
    "line2": "rgba(236, 231, 220, 0.16)",
    "text": "#ece7dc",
    "muted": "#9a927f",
    "faint": "#615b4d",
    "accent": "#e8491d",
    "accent-ink": "#1c0e08",
    "accent-soft": "#f4a68c",
    "chip-bg": "rgba(232, 73, 29, 0.15)",
    "brass": "#b08d3e",
    "brass-soft": "#d9bc7a",
    "brass-bg": "rgba(176, 141, 62, 0.18)",
    "tabbar": "#0b0906"
  },
  "fontSize": {
    "mega": [
      "84px",
      {
        "lineHeight": "1",
        "fontWeight": "700",
        "letterSpacing": "-0.01em"
      }
    ],
    "hero": [
      "50px",
      {
        "lineHeight": "0.98",
        "fontWeight": "700",
        "letterSpacing": "-0.01em"
      }
    ],
    "fig": [
      "30px",
      {
        "lineHeight": "1.05",
        "fontWeight": "700"
      }
    ],
    "num": [
      "21px",
      {
        "lineHeight": "1.1",
        "fontWeight": "600"
      }
    ],
    "title": [
      "17px",
      {
        "lineHeight": "1.2",
        "fontWeight": "600",
        "letterSpacing": "0.01em"
      }
    ],
    "body": [
      "14px",
      {
        "lineHeight": "1.5",
        "fontWeight": "400"
      }
    ],
    "label": [
      "13px",
      {
        "lineHeight": "1.4",
        "fontWeight": "400"
      }
    ],
    "kick": [
      "10px",
      {
        "lineHeight": "1.2",
        "fontWeight": "500",
        "letterSpacing": "0.14em"
      }
    ],
    "meta": [
      "11px",
      {
        "lineHeight": "1.2",
        "fontWeight": "500"
      }
    ],
    "nano": [
      "9px",
      {
        "lineHeight": "1.1",
        "fontWeight": "500",
        "letterSpacing": "0.1em"
      }
    ]
  },
  "borderRadius": {
    "card": "16px",
    "ctl": "12px",
    "chip": "6px",
    "pill": "999px"
  },
  "spacing": {
    "gutter": "18px",
    "authGutter": "22px",
    "cardPad": "16px",
    "touch": "48px",
    "tabBar": "58px",
    "stepperZone": "82px",
    "commitBar": "70px",
    "otpCell": "58px"
  },
  "fontFamily": {
    "display": [
      "Saira Semi Condensed"
    ],
    "body": [
      "Hanken Grotesk"
    ],
    "mono": [
      "IBM Plex Mono"
    ]
  },
  "motion": {
    "press": 80,
    "instant": 90,
    "transition": 160,
    "celebration": 1140,
    "fill": 500,
    "ring": 1000
  },
  "typeFace": {
    "mega": "display",
    "hero": "display",
    "fig": "display",
    "num": "display",
    "title": "display",
    "body": "body",
    "label": "body",
    "kick": "mono",
    "meta": "mono",
    "nano": "mono"
  },
  "typeCase": {
    "mega": false,
    "hero": true,
    "fig": false,
    "num": false,
    "title": true,
    "body": false,
    "label": false,
    "kick": true,
    "meta": false,
    "nano": true
  },
  "typeTabular": {
    "mega": true,
    "hero": true,
    "fig": true,
    "num": true,
    "title": false,
    "body": false,
    "label": false,
    "kick": false,
    "meta": true,
    "nano": false
  }
}
