// GENERATED by scripts/build_logo.py — do not edit by hand.
//
// The Latin wordmark: `w`, a vermilion plate standing in for the `a`, `zn`.
// Sora 800 outlines, composed to the brand sheet's own metrics and trimmed to
// the ink, so `height` on <Wordmark> is the height of what you see.
//
// The letters take the caller's colour; the plate and its bar are always
// accent. Both plate parts are one visual object — the ring needs `evenodd`
// so the ground shows through the hole, the bar must NOT be in that path or
// the even-odd rule would punch it back out again.

/**
 * The composed lockup's ink bounds. The paths keep the coordinates they were
 * composed in and the viewBox moves to meet them, so nothing needs a
 * transform — but the share card draws these on a canvas, which has no
 * viewBox, so it needs the origin as numbers.
 */
export const LATIN_X = 1.79
export const LATIN_Y = 34.56
export const LATIN_W = 331.06
export const LATIN_H = 76.26

/** The same four numbers as an SVG `viewBox`. */
export const LATIN_VIEWBOX = `${LATIN_X} ${LATIN_Y} ${LATIN_W} ${LATIN_H}`

/** `w` and `zn`, already kerned and tracked. Fill with the letter colour. */
export const LATIN_LETTERS_D =
  'M36.1 107.52 48.64 39.17H72.96L87.3 107.52H69.63L54.78 39.68H65.54L51.97 107.52ZM31.74 107.52 31.62 88.06H45.7L45.82 107.52ZM20.35 107.52 1.79 36.86H24.58L41.73 107.52ZM75.9 107.52 76.03 88.06H90.11L89.98 107.52ZM81.54 107.52 97.02 36.86H118.27L101.38 107.52Z M201.53 107.52V93.06L232.89 55.3V57.34L229.56 53.25L232.12 54.53H201.78V36.86H259.13V51.33L227.77 89.09V87.04L231.1 91.14L228.54 89.86H259.9V107.52Z M264.5 107.52V36.86H282.94V67.2H281.91Q281.91 56.19 284.73 48.96Q287.54 41.73 293.11 38.14Q298.68 34.56 306.62 34.56H307.64Q319.67 34.56 326.26 42.56Q332.86 50.56 332.86 67.07V107.52H309.56V66.43Q309.56 61.57 306.68 58.43Q303.8 55.3 298.81 55.3Q293.82 55.3 290.81 58.43Q287.8 61.57 287.8 66.69V107.52Z'

/** The plate that replaces the `a`: ring and hole, needs `fill-rule=evenodd`. */
export const LATIN_PLATE_D =
  'M122.69 80.00 a30.82 30.82 0 1 0 61.64 0 a30.82 30.82 0 1 0 -61.64 0 Z M142.79 77.32 a10.72 10.72 0 1 0 21.44 0 a10.72 10.72 0 1 0 -21.44 0 Z'

/** The bar stub the plate is loaded onto. Solid — no even-odd. */
export const LATIN_BAR_D =
  'M185.00 49.18 a4.69 4.69 0 0 1 4.69 4.69 v52.26 a4.69 4.69 0 0 1 -4.69 4.69 a4.69 4.69 0 0 1 -4.69 -4.69 v-52.26 a4.69 4.69 0 0 1 4.69 -4.69 Z'
