import type { CSSProperties } from 'react'
import {
  DOT_D,
  LETTERS_D,
  LETTER_STROKE,
  MARK_H,
  MARK_W,
  SHAFT,
} from './wordmark-paths'
import {
  LATIN_BAR_D,
  LATIN_LETTERS_D,
  LATIN_PLATE_D,
  LATIN_VIEWBOX,
} from './wordmark-latin-paths'
import { useLocale } from '../lib/locale-context'

/**
 * The Wazn wordmark, in whichever script the reader is in.
 *
 * v3 "The Plate" gives the brand a Latin lockup: `w`, a vermilion plate
 * standing in for the `a`, `zn` — the word carries its own weight. That leads
 * in English. The وزن barbell that was the whole mark through v2 is not
 * retired; the brand sheet calls it the soul and keeps it for the Arabic
 * locale, the splash and About, which is what `soul` forces.
 *
 * Neither mark is live text. Sora and Aref Ruqaa both ship `font-display:
 * swap`, so a wordmark set in real type renders as a fallback on first paint
 * and then reflows — the one element on screen that must never do that. Both
 * are outlines generated by scripts/build_logo.py from the app's own font
 * files, so what the mark is made of and what the UI is set in cannot drift.
 *
 * Letters take `currentColor`. The plate, the shaft and the ز plate face are
 * always accent: the iron is the one thing that is never the text colour.
 */
/**
 * How much taller the barbell has to be drawn to carry the same weight as the
 * Latin lockup beside it.
 *
 * `height` is the Latin mark's ink height, and the two marks are different
 * objects: `wazn` is a band of lowercase letters, وزن is three letters with a
 * bar running past both ends and air baked into its viewBox. Sized to the same
 * number the barbell reads as a caption. This keeps one `height` at each call
 * site meaning one optical size in both locales.
 */
const SOUL_SCALE = 2.2

export function Wordmark({
  height = 16,
  soul = false,
  className,
  style,
}: {
  /** The Latin mark's ink height. The barbell is scaled to match optically. */
  height?: number
  /** Force the وزن barbell — the splash and About lead with it in any locale. */
  soul?: boolean
  className?: string
  style?: CSSProperties
}) {
  const { t, locale } = useLocale()
  const shared = {
    className,
    style: { width: 'auto', display: 'block', ...style },
    role: 'img' as const,
    'aria-label': t('wordmark.label'),
  }

  if (soul || locale === 'ar') {
    return (
      <svg viewBox={`0 0 ${MARK_W} ${MARK_H}`} height={height * SOUL_SCALE} {...shared}>
        <line
          x1={SHAFT.x0}
          y1={SHAFT.y}
          x2={SHAFT.x1}
          y2={SHAFT.y}
          stroke="var(--color-accent)"
          strokeWidth={SHAFT.t}
          strokeLinecap="round"
        />
        <path
          d={LETTERS_D}
          fill="currentColor"
          stroke="currentColor"
          strokeWidth={LETTER_STROKE}
          strokeLinejoin="round"
        />
        <path d={DOT_D} fill="var(--color-accent)" fillRule="evenodd" />
      </svg>
    )
  }

  return (
    <svg viewBox={LATIN_VIEWBOX} height={height} {...shared}>
      <path d={LATIN_LETTERS_D} fill="currentColor" />
      {/* Two paths, not one: the ring needs even-odd so the ground shows
          through the hole, and a bar folded into that path would be punched
          back out by the same rule. */}
      <path d={LATIN_PLATE_D} fill="var(--color-accent)" fillRule="evenodd" />
      <path d={LATIN_BAR_D} fill="var(--color-accent)" />
    </svg>
  )
}
