import type { MuscleGroup } from '@wazn/core/types'

/**
 * Hardcoded exercise -> muscle group table. Every name in the Hevy export is
 * listed here, plus the three program lifts that are not in the CSV. Groups are
 * limited to the eleven the schema allows; nothing else is invented.
 */
export const MUSCLE_GROUPS: Record<string, MuscleGroup> = {
  '21s Bicep Curl': 'biceps',
  'Air Bike': 'cardio',
  'Around The World': 'chest',
  'Back Extension (Machine)': 'back',
  'Back Extension (Weighted Hyperextension)': 'back',
  'Behind the Back Curl (Cable)': 'biceps',
  'Behind the Back Wrist Curl (Barbell)': 'biceps',
  'Bench Dip': 'triceps',
  'Bench Press (Barbell)': 'chest',
  'Bench Press (Cable)': 'chest',
  'Bench Press (Dumbbell)': 'chest',
  'Bench Press - Close Grip (Barbell)': 'triceps',
  'Bent Over Row (Barbell)': 'back',
  'Bicep Curl (Barbell)': 'biceps',
  'Bicep Curl (Cable)': 'biceps',
  'Bicep Curl (Dumbbell)': 'biceps',
  'Bicycle Crunch': 'core',
  'Bulgarian Split Squat (Dumbbell)': 'quads',
  'Cable Crunch': 'core',
  'Cable Fly Crossovers': 'chest',
  'Calf Press (Machine)': 'calves',
  'Chest Dip': 'chest',
  'Chest Fly (Dumbbell)': 'chest',
  'Chest Fly (Machine)': 'chest',
  'Chest Press (Machine)': 'chest',
  'Chest Supported Incline Row (Dumbbell)': 'back',
  'Chest Supported Row (Machine)': 'back',
  'Chin Up': 'back',
  'Concentration Curl': 'biceps',
  Crunch: 'core',
  'Crunch (Machine)': 'core',
  'Crunch (Weighted)': 'core',
  'Deadlift (Barbell)': 'back',
  'Deadlift (Dumbbell)': 'back',
  'Decline Crunch (Weighted)': 'core',
  'Dumbbell Row': 'back',
  'Dumbbell Squeeze Press': 'chest',
  'EZ Bar Biceps Curl': 'biceps',
  'Elliptical Trainer': 'cardio',
  'Face Pull': 'shoulders',
  'Front Raise (Cable)': 'shoulders',
  'Front Raise (Dumbbell)': 'shoulders',
  'Front Squat': 'quads',
  'Full Squat': 'quads',
  'Glute Bridge': 'glutes',
  'Glute Ham Raise': 'hamstrings',
  'Hammer Curl (Dumbbell)': 'biceps',
  'Hanging Knee Raise': 'core',
  'Hex Press (Dumbbell)': 'chest',
  'Hip Abduction (Machine)': 'glutes',
  'Hip Adduction (Machine)': 'quads',
  'Hip Thrust (Machine)': 'glutes',
  'Hip Thrust (Smith Machine)': 'glutes',
  'Incline Bench Press (Barbell)': 'chest',
  'Incline Bench Press (Dumbbell)': 'chest',
  'Incline Bench Press (Smith Machine)': 'chest',
  'Iso-Lateral Chest Press (Machine)': 'chest',
  'Iso-Lateral High Row (Machine)': 'back',
  'Iso-Lateral Row (Machine)': 'back',
  'Knee Raise Parallel Bars': 'core',
  'Landmine Row': 'back',
  'Lat Pulldown (Cable)': 'back',
  'Lat Pulldown (Machine)': 'back',
  'Lat Pulldown - Close Grip (Cable)': 'back',
  'Lateral Raise (Dumbbell)': 'shoulders',
  'Leg Extension (Machine)': 'quads',
  'Leg Press (Machine)': 'quads',
  'Low Cable Fly Crossovers': 'chest',
  Lunge: 'quads',
  'Lunge (Barbell)': 'quads',
  'Lunge (Dumbbell)': 'quads',
  'Lying Leg Curl (Machine)': 'hamstrings',
  'Overhead Press (Barbell)': 'shoulders',
  'Overhead Triceps Extension (Cable)': 'triceps',
  'Pendlay Row (Barbell)': 'back',
  Plank: 'core',
  'Preacher Curl (Dumbbell)': 'biceps',
  'Preacher Curl (Machine)': 'biceps',
  'Pull Up': 'back',
  'Pullover (Dumbbell)': 'back',
  'Pullover (Machine)': 'back',
  'Push Up': 'chest',
  'Rear Delt Reverse Fly (Cable)': 'shoulders',
  'Rear Delt Reverse Fly (Machine)': 'shoulders',
  'Rear Kick (Machine)': 'glutes',
  'Reverse Curl (Cable)': 'biceps',
  'Reverse Grip Concentration Curl': 'biceps',
  'Reverse Grip Lat Pulldown (Cable)': 'back',
  'Romanian Deadlift (Barbell)': 'hamstrings',
  'Romanian Deadlift (Dumbbell)': 'hamstrings',
  'Seated Cable Row - Bar Grip': 'back',
  'Seated Cable Row - Bar Wide Grip': 'back',
  'Seated Cable Row - V Grip (Cable)': 'back',
  'Seated Calf Raise': 'calves',
  'Seated Dip Machine': 'triceps',
  'Seated Incline Curl (Dumbbell)': 'biceps',
  'Seated Lateral Raise (Dumbbell)': 'shoulders',
  'Seated Leg Curl (Machine)': 'hamstrings',
  'Seated Row (Machine)': 'back',
  'Seated Shoulder Press (Machine)': 'shoulders',
  'Seated Wrist Extension (Barbell)': 'triceps',
  'Shoulder Press (Dumbbell)': 'shoulders',
  'Shoulder Press (Machine Plates)': 'shoulders',
  'Shrug (Barbell)': 'back',
  'Shrug (Dumbbell)': 'back',
  'Shrug (Machine)': 'back',
  'Side Bend': 'core',
  'Side Bend (Dumbbell)': 'core',
  'Single Arm Cable Row': 'back',
  'Single Arm Landmine Press (Barbell)': 'shoulders',
  'Single Arm Lateral Raise (Cable)': 'shoulders',
  'Single Leg Standing Calf Raise (Machine)': 'calves',
  'Sit Up (Weighted)': 'core',
  'Skullcrusher (Barbell)': 'triceps',
  'Skullcrusher (Dumbbell)': 'triceps',
  'Squat (Barbell)': 'quads',
  'Squat (Smith Machine)': 'quads',
  'Stair Machine (Floors)': 'cardio',
  'Stair Machine (Steps)': 'cardio',
  'Standing Calf Raise': 'calves',
  'Standing Calf Raise (Machine)': 'calves',
  'Straight Arm Lat Pulldown (Cable)': 'back',
  'Sumo Squat (Dumbbell)': 'quads',
  'T Bar Row': 'back',
  Treadmill: 'cardio',
  'Triceps Extension (Cable)': 'triceps',
  'Triceps Extension (Dumbbell)': 'triceps',
  'Triceps Kickback (Cable)': 'triceps',
  'Triceps Kickback (Dumbbell)': 'triceps',
  'Triceps Pressdown': 'triceps',
  'Triceps Pushdown': 'triceps',
  'Triceps Rope Pushdown': 'triceps',
  'Walking Lunge (Dumbbell)': 'quads',
  'Warm Up': 'cardio',
}

/** Program lifts the user trains that never appear in the Hevy export. */
export const EXTRA_EXERCISES = [
  'Hanging Knee Raise',
  'Chin Up',
  'Chest Supported Row (Machine)',
] as const

/**
 * Equipment comes from the parenthetical suffix only:
 * (Barbell) (Dumbbell) (Cable) (Machine). Anything else is bodyweight, except
 * cardio machines, which are "other".
 */
export function deriveEquipment(name: string, group: MuscleGroup): string {
  const suffix = name.match(/\(([^)]+)\)\s*$/)?.[1] ?? ''
  if (/barbell/i.test(suffix)) return 'barbell'
  if (/dumbbell/i.test(suffix)) return 'dumbbell'
  if (/cable/i.test(suffix)) return 'cable'
  if (/machine/i.test(suffix)) return 'machine'
  return group === 'cardio' ? 'other' : 'bodyweight'
}
